"""Byte-level constants defined by the Pi--STM32 UART v1 contract."""

PROTOCOL_VERSION = 0x0001

MESSAGE_COMMAND = 0x01
MESSAGE_TELEMETRY = 0x02
MESSAGE_CONFIG = 0x03

COMMAND_PAYLOAD_LENGTH = 20
TELEMETRY_PAYLOAD_LENGTH = 65
CONFIG_REQUEST_PAYLOAD_LENGTH = 40
CONFIG_STATUS_PAYLOAD_LENGTH = 50

HEADER_LENGTH = 4
CRC_LENGTH = 2
MAX_RAW_FRAME_LENGTH = 96
MAX_WIRE_FRAME_LENGTH = 98
WIRE_DELIMITER = 0x00

CONFIG_ACCEPTED = 0x01
CONFIG_REJECTED = 0x02

REJECT_NONE = 0x00
REJECT_HASH_MISMATCH = 0x01
REJECT_LOCAL_CONFIG_INVALID = 0x02

VALID_MESSAGE_TYPES = frozenset((MESSAGE_COMMAND, MESSAGE_TELEMETRY, MESSAGE_CONFIG))
