/*
 * Host-only UART v1 codec test.  Expected byte arrays below are copied from
 * docs/Pi_STM32_UART_v1_Golden_Vectors.md, not generated by this codec.
 * I7/I8/I9 (sequence/epoch state) intentionally belong to a future
 * ControlSafety/session test and are not implemented here.
 */

#include "communication.h"

#include <assert.h>
#include <math.h>
#include <stdio.h>
#include <string.h>

#define ARRAY_LENGTH(array) (sizeof(array) / sizeof((array)[0]))

static const uint8_t v1_payload[] = {
    0x40, 0x30, 0x20, 0x10, 0x44, 0x33, 0x22, 0x11, 0x00, 0x00,
    0xa0, 0x3f, 0x00, 0x00, 0x00, 0xbf, 0x00, 0x00, 0x40, 0x3f
};
static const uint8_t v1_raw[] = {
    0x01, 0x00, 0x01, 0x14, 0x40, 0x30, 0x20, 0x10, 0x44, 0x33,
    0x22, 0x11, 0x00, 0x00, 0xa0, 0x3f, 0x00, 0x00, 0x00, 0xbf,
    0x00, 0x00, 0x40, 0x3f, 0x30, 0x6e
};
static const uint8_t v1_wire[] = {
    0x02, 0x01, 0x0b, 0x01, 0x14, 0x40, 0x30, 0x20, 0x10, 0x44,
    0x33, 0x22, 0x11, 0x01, 0x03, 0xa0, 0x3f, 0x01, 0x01, 0x02,
    0xbf, 0x01, 0x05, 0x40, 0x3f, 0x30, 0x6e, 0x00
};

static const uint8_t v2_payload[] = {
    0x04, 0x03, 0x02, 0x01, 0x44, 0x33, 0x22, 0x11, 0x00, 0x01,
    0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b,
    0x0c, 0x0d, 0x0e, 0x0f, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15,
    0x16, 0x17, 0x18, 0x19, 0x1a, 0x1b, 0x1c, 0x1d, 0x1e, 0x1f
};
static const uint8_t v2_raw[] = {
    0x01, 0x00, 0x03, 0x28, 0x04, 0x03, 0x02, 0x01, 0x44, 0x33,
    0x22, 0x11, 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07,
    0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f, 0x10, 0x11,
    0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1a, 0x1b,
    0x1c, 0x1d, 0x1e, 0x1f, 0x7b, 0xe7
};
static const uint8_t v2_wire[] = {
    0x02, 0x01, 0x0b, 0x03, 0x28, 0x04, 0x03, 0x02, 0x01, 0x44,
    0x33, 0x22, 0x11, 0x22, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06,
    0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f, 0x10,
    0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1a,
    0x1b, 0x1c, 0x1d, 0x1e, 0x1f, 0x7b, 0xe7, 0x00
};

static const uint8_t v3_payload[] = {
    0x04, 0x03, 0x02, 0x01, 0x44, 0x33, 0x22, 0x11, 0x00, 0x01,
    0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b,
    0x0c, 0x0d, 0x0e, 0x0f, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15,
    0x16, 0x17, 0x18, 0x19, 0x1a, 0x1b, 0x1c, 0x1d, 0x1e, 0x1f,
    0x08, 0x07, 0x06, 0x05, 0x04, 0x03, 0x02, 0x01, 0x01, 0x00
};
static const uint8_t v3_raw[] = {
    0x01, 0x00, 0x03, 0x32, 0x04, 0x03, 0x02, 0x01, 0x44, 0x33,
    0x22, 0x11, 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07,
    0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f, 0x10, 0x11,
    0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1a, 0x1b,
    0x1c, 0x1d, 0x1e, 0x1f, 0x08, 0x07, 0x06, 0x05, 0x04, 0x03,
    0x02, 0x01, 0x01, 0x00, 0xa7, 0x93
};
static const uint8_t v3_wire[] = {
    0x02, 0x01, 0x0b, 0x03, 0x32, 0x04, 0x03, 0x02, 0x01, 0x44,
    0x33, 0x22, 0x11, 0x29, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06,
    0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f, 0x10,
    0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1a,
    0x1b, 0x1c, 0x1d, 0x1e, 0x1f, 0x08, 0x07, 0x06, 0x05, 0x04,
    0x03, 0x02, 0x01, 0x01, 0x03, 0xa7, 0x93, 0x00
};

static const uint8_t v4_payload[] = {
    0x05, 0x03, 0x02, 0x01, 0x44, 0x33, 0x22, 0x11, 0x00, 0x01,
    0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b,
    0x0c, 0x0d, 0x0e, 0x0f, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15,
    0x16, 0x17, 0x18, 0x19, 0x1a, 0x1b, 0x1c, 0x1d, 0x1e, 0x1f,
    0x08, 0x07, 0x06, 0x05, 0x04, 0x03, 0x02, 0x01, 0x02, 0x01
};
static const uint8_t v4_raw[] = {
    0x01, 0x00, 0x03, 0x32, 0x05, 0x03, 0x02, 0x01, 0x44, 0x33,
    0x22, 0x11, 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07,
    0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f, 0x10, 0x11,
    0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1a, 0x1b,
    0x1c, 0x1d, 0x1e, 0x1f, 0x08, 0x07, 0x06, 0x05, 0x04, 0x03,
    0x02, 0x01, 0x02, 0x01, 0xa3, 0xc4
};
static const uint8_t v4_wire[] = {
    0x02, 0x01, 0x0b, 0x03, 0x32, 0x05, 0x03, 0x02, 0x01, 0x44,
    0x33, 0x22, 0x11, 0x2c, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06,
    0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f, 0x10,
    0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1a,
    0x1b, 0x1c, 0x1d, 0x1e, 0x1f, 0x08, 0x07, 0x06, 0x05, 0x04,
    0x03, 0x02, 0x01, 0x02, 0x01, 0xa3, 0xc4, 0x00
};

static const uint8_t v5_payload[] = {
    0x06, 0x03, 0x02, 0x01, 0x44, 0x33, 0x22, 0x11, 0x00, 0x01,
    0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b,
    0x0c, 0x0d, 0x0e, 0x0f, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15,
    0x16, 0x17, 0x18, 0x19, 0x1a, 0x1b, 0x1c, 0x1d, 0x1e, 0x1f,
    0x08, 0x07, 0x06, 0x05, 0x04, 0x03, 0x02, 0x01, 0x02, 0x02
};
static const uint8_t v5_raw[] = {
    0x01, 0x00, 0x03, 0x32, 0x06, 0x03, 0x02, 0x01, 0x44, 0x33,
    0x22, 0x11, 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07,
    0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f, 0x10, 0x11,
    0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1a, 0x1b,
    0x1c, 0x1d, 0x1e, 0x1f, 0x08, 0x07, 0x06, 0x05, 0x04, 0x03,
    0x02, 0x01, 0x02, 0x02, 0x5a, 0xc2
};
static const uint8_t v5_wire[] = {
    0x02, 0x01, 0x0b, 0x03, 0x32, 0x06, 0x03, 0x02, 0x01, 0x44,
    0x33, 0x22, 0x11, 0x2c, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06,
    0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f, 0x10,
    0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1a,
    0x1b, 0x1c, 0x1d, 0x1e, 0x1f, 0x08, 0x07, 0x06, 0x05, 0x04,
    0x03, 0x02, 0x01, 0x02, 0x02, 0x5a, 0xc2, 0x00
};

static const uint8_t v6_payload[] = {
    0x0d, 0x0c, 0x0b, 0x0a, 0x08, 0x07, 0x06, 0x05, 0x04, 0x03,
    0x02, 0x01, 0x44, 0x33, 0x22, 0x11, 0x07, 0x06, 0x05, 0x04,
    0x03, 0x02, 0x01, 0x00, 0x15, 0xcd, 0x5b, 0x07, 0x00, 0x00,
    0x00, 0x00, 0xd6, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
    0xea, 0x16, 0xb0, 0x4c, 0x02, 0x00, 0x00, 0x00, 0x16, 0xe9,
    0x4f, 0xb3, 0xfd, 0xff, 0xff, 0xff, 0x40, 0x30, 0x20, 0x10,
    0x02, 0x08, 0x00, 0x00, 0x01
};
static const uint8_t v6_raw[] = {
    0x01, 0x00, 0x02, 0x41, 0x0d, 0x0c, 0x0b, 0x0a, 0x08, 0x07,
    0x06, 0x05, 0x04, 0x03, 0x02, 0x01, 0x44, 0x33, 0x22, 0x11,
    0x07, 0x06, 0x05, 0x04, 0x03, 0x02, 0x01, 0x00, 0x15, 0xcd,
    0x5b, 0x07, 0x00, 0x00, 0x00, 0x00, 0xd6, 0xff, 0xff, 0xff,
    0xff, 0xff, 0xff, 0xff, 0xea, 0x16, 0xb0, 0x4c, 0x02, 0x00,
    0x00, 0x00, 0x16, 0xe9, 0x4f, 0xb3, 0xfd, 0xff, 0xff, 0xff,
    0x40, 0x30, 0x20, 0x10, 0x02, 0x08, 0x00, 0x00, 0x01, 0xdd,
    0x12
};
static const uint8_t v6_wire[] = {
    0x02, 0x01, 0x1a, 0x02, 0x41, 0x0d, 0x0c, 0x0b, 0x0a, 0x08,
    0x07, 0x06, 0x05, 0x04, 0x03, 0x02, 0x01, 0x44, 0x33, 0x22,
    0x11, 0x07, 0x06, 0x05, 0x04, 0x03, 0x02, 0x01, 0x05, 0x15,
    0xcd, 0x5b, 0x07, 0x01, 0x01, 0x01, 0x0e, 0xd6, 0xff, 0xff,
    0xff, 0xff, 0xff, 0xff, 0xff, 0xea, 0x16, 0xb0, 0x4c, 0x02, 0x01,
    0x01, 0x0f, 0x16, 0xe9, 0x4f, 0xb3, 0xfd, 0xff, 0xff, 0xff,
    0x40, 0x30, 0x20, 0x10, 0x02, 0x08, 0x01, 0x04, 0x01, 0xdd,
    0x12, 0x00
};

static const uint8_t i1_wire[] = {
    0x02, 0x01, 0x0b, 0x01, 0x14, 0x40, 0x30, 0x20, 0x10, 0x44,
    0x33, 0x22, 0x11, 0x01, 0x03, 0xa0, 0x3f, 0x01, 0x01, 0x02,
    0xbf, 0x01, 0x05, 0x40, 0x3f, 0x31, 0x6e, 0x00
};
static const uint8_t i2_wire[] = {0x02, 0x00};
static const uint8_t i3_wire[] = {
    0x02, 0x01, 0x0b, 0x01, 0x13, 0x40, 0x30, 0x20, 0x10, 0x44,
    0x33, 0x22, 0x11, 0x01, 0x03, 0xa0, 0x3f, 0x01, 0x01, 0x02,
    0xbf, 0x01, 0x05, 0x40, 0x3f, 0xb0, 0x67, 0x00
};
static const uint8_t i4_wire[] = {
    0x02, 0x02, 0x0b, 0x01, 0x14, 0x40, 0x30, 0x20, 0x10, 0x44,
    0x33, 0x22, 0x11, 0x01, 0x03, 0xa0, 0x3f, 0x01, 0x01, 0x02,
    0xbf, 0x01, 0x05, 0x40, 0x3f, 0x35, 0x37, 0x00
};
static const uint8_t i5_wire[] = {
    0x02, 0x01, 0x0b, 0x7f, 0x14, 0x40, 0x30, 0x20, 0x10, 0x44,
    0x33, 0x22, 0x11, 0x01, 0x03, 0xa0, 0x3f, 0x01, 0x01, 0x02,
    0xbf, 0x01, 0x05, 0x40, 0x3f, 0xd3, 0x4e, 0x00
};
static const uint8_t i6_wire[] = {
    0x02, 0x01, 0x0b, 0x01, 0x14, 0x41, 0x30, 0x20, 0x10, 0x44,
    0x33, 0x22, 0x11, 0x01, 0x03, 0xc0, 0x7f, 0x01, 0x01, 0x02,
    0xbf, 0x01, 0x05, 0x40, 0x3f, 0x4d, 0x4f, 0x00
};

static void expect_frame_bytes(uint8_t message_type, const uint8_t *payload,
                               size_t payload_length, const uint8_t *raw_expected,
                               size_t raw_expected_length, const uint8_t *wire_expected,
                               size_t wire_expected_length)
{
    uint8_t raw[MECANUM_UART_V1_RAW_BUFFER_MINIMUM];
    uint8_t wire[MECANUM_UART_V1_COBS_BUFFER_MINIMUM];
    size_t raw_length = 0U;
    size_t wire_length = 0U;

    assert(mecanum_uart_v1_build_raw_frame(message_type, payload, payload_length,
                                            raw, sizeof(raw), &raw_length)
           == MECANUM_UART_V1_OK);
    assert(raw_length == raw_expected_length);
    assert(memcmp(raw, raw_expected, raw_expected_length) == 0);
    assert(mecanum_uart_v1_build_wire_frame(message_type, payload, payload_length,
                                             wire, sizeof(wire), &wire_length)
           == MECANUM_UART_V1_OK);
    assert(wire_length == wire_expected_length);
    assert(memcmp(wire, wire_expected, wire_expected_length) == 0);
}

static mecanum_uart_v1_frame_t decode_valid(const uint8_t *wire, size_t wire_length,
                                             uint8_t expected_type,
                                             const uint8_t *expected_payload,
                                             size_t expected_payload_length)
{
    mecanum_uart_v1_frame_t frame;

    assert(mecanum_uart_v1_decode_wire_frame(wire, wire_length, &frame)
           == MECANUM_UART_V1_OK);
    assert(frame.protocol_version == MECANUM_UART_V1_PROTOCOL_VERSION);
    assert(frame.message_type == expected_type);
    assert(frame.payload_length == expected_payload_length);
    assert(memcmp(frame.payload, expected_payload, expected_payload_length) == 0);
    return frame;
}

static void test_v1_command(void)
{
    mecanum_uart_v1_command_t command = {
        UINT32_C(0x10203040), UINT32_C(0x11223344), 1.25F, -0.5F, 0.75F
    };
    mecanum_uart_v1_command_t decoded;
    mecanum_uart_v1_frame_t frame;
    uint8_t payload[MECANUM_UART_V1_COMMAND_PAYLOAD_LENGTH];

    assert(mecanum_uart_v1_serialize_command(&command, payload, sizeof(payload))
           == MECANUM_UART_V1_OK);
    assert(memcmp(payload, v1_payload, sizeof(payload)) == 0);
    expect_frame_bytes(MECANUM_UART_V1_MESSAGE_COMMAND, v1_payload, sizeof(v1_payload),
                       v1_raw, sizeof(v1_raw), v1_wire, sizeof(v1_wire));
    frame = decode_valid(v1_wire, sizeof(v1_wire), MECANUM_UART_V1_MESSAGE_COMMAND,
                         v1_payload, sizeof(v1_payload));
    assert(mecanum_uart_v1_parse_command(frame.payload, frame.payload_length, &decoded)
           == MECANUM_UART_V1_OK);
    assert(decoded.command_sequence == command.command_sequence);
    assert(decoded.reset_epoch == command.reset_epoch);
    assert(decoded.vx_mps == command.vx_mps && decoded.vy_mps == command.vy_mps
           && decoded.wz_radps == command.wz_radps);
    assert(mecanum_uart_v1_command_is_finite(&decoded));
}

static void test_v2_config_request(void)
{
    mecanum_uart_v1_config_request_t request;
    mecanum_uart_v1_config_request_t decoded;
    mecanum_uart_v1_frame_t frame;
    uint8_t payload[MECANUM_UART_V1_CONFIG_REQUEST_PAYLOAD_LENGTH];
    size_t index;

    request.config_sequence = UINT32_C(0x01020304);
    request.reset_epoch = UINT32_C(0x11223344);
    for (index = 0U; index < sizeof(request.hardware_config_hash); ++index) {
        request.hardware_config_hash[index] = (uint8_t)index;
    }
    assert(mecanum_uart_v1_serialize_config_request(&request, payload, sizeof(payload))
           == MECANUM_UART_V1_OK);
    assert(memcmp(payload, v2_payload, sizeof(payload)) == 0);
    expect_frame_bytes(MECANUM_UART_V1_MESSAGE_CONFIG, v2_payload, sizeof(v2_payload),
                       v2_raw, sizeof(v2_raw), v2_wire, sizeof(v2_wire));
    frame = decode_valid(v2_wire, sizeof(v2_wire), MECANUM_UART_V1_MESSAGE_CONFIG,
                         v2_payload, sizeof(v2_payload));
    assert(mecanum_uart_v1_parse_config_request(frame.payload, frame.payload_length, &decoded)
           == MECANUM_UART_V1_OK);
    assert(decoded.config_sequence == request.config_sequence);
    assert(decoded.reset_epoch == request.reset_epoch);
    assert(memcmp(decoded.hardware_config_hash, request.hardware_config_hash,
                  sizeof(decoded.hardware_config_hash)) == 0);
}

static void test_config_status_vector(const uint8_t *payload_expected,
                                      const uint8_t *raw_expected, size_t raw_length,
                                      const uint8_t *wire_expected, size_t wire_length,
                                      uint32_t config_sequence, uint8_t config_status,
                                      uint8_t reject_reason)
{
    mecanum_uart_v1_config_status_t status;
    mecanum_uart_v1_config_status_t decoded;
    mecanum_uart_v1_frame_t frame;
    uint8_t payload[MECANUM_UART_V1_CONFIG_STATUS_PAYLOAD_LENGTH];
    size_t index;

    status.config_sequence = config_sequence;
    status.reset_epoch = UINT32_C(0x11223344);
    for (index = 0U; index < sizeof(status.hardware_config_hash); ++index) {
        status.hardware_config_hash[index] = (uint8_t)index;
    }
    status.mcu_boot_id = UINT64_C(0x0102030405060708);
    status.config_status = config_status;
    status.reject_reason = reject_reason;
    assert(mecanum_uart_v1_serialize_config_status(&status, payload, sizeof(payload))
           == MECANUM_UART_V1_OK);
    assert(memcmp(payload, payload_expected, sizeof(payload)) == 0);
    expect_frame_bytes(MECANUM_UART_V1_MESSAGE_CONFIG, payload_expected,
                       sizeof(payload), raw_expected, raw_length, wire_expected,
                       wire_length);
    frame = decode_valid(wire_expected, wire_length, MECANUM_UART_V1_MESSAGE_CONFIG,
                         payload_expected, sizeof(payload));
    assert(mecanum_uart_v1_parse_config_status(frame.payload, frame.payload_length, &decoded)
           == MECANUM_UART_V1_OK);
    assert(decoded.config_sequence == status.config_sequence);
    assert(decoded.reset_epoch == status.reset_epoch);
    assert(decoded.mcu_boot_id == status.mcu_boot_id);
    assert(decoded.config_status == status.config_status);
    assert(decoded.reject_reason == status.reject_reason);
    assert(memcmp(decoded.hardware_config_hash, status.hardware_config_hash,
                  sizeof(decoded.hardware_config_hash)) == 0);
}

static void test_v6_telemetry(void)
{
    mecanum_uart_v1_telemetry_t telemetry = {
        UINT32_C(0x0a0b0c0d), UINT64_C(0x0102030405060708), UINT32_C(0x11223344),
        UINT64_C(0x0001020304050607), INT64_C(123456789), -INT64_C(42),
        INT64_C(9876543210), -INT64_C(9876543210), UINT32_C(0x10203040),
        UINT32_C(2050), UINT8_C(1)
    };
    mecanum_uart_v1_telemetry_t decoded;
    mecanum_uart_v1_frame_t frame;
    uint8_t payload[MECANUM_UART_V1_TELEMETRY_PAYLOAD_LENGTH];

    assert(mecanum_uart_v1_serialize_telemetry(&telemetry, payload, sizeof(payload))
           == MECANUM_UART_V1_OK);
    assert(memcmp(payload, v6_payload, sizeof(payload)) == 0);
    expect_frame_bytes(MECANUM_UART_V1_MESSAGE_TELEMETRY, v6_payload, sizeof(v6_payload),
                       v6_raw, sizeof(v6_raw), v6_wire, sizeof(v6_wire));
    frame = decode_valid(v6_wire, sizeof(v6_wire), MECANUM_UART_V1_MESSAGE_TELEMETRY,
                         v6_payload, sizeof(v6_payload));
    assert(mecanum_uart_v1_parse_telemetry(frame.payload, frame.payload_length, &decoded)
           == MECANUM_UART_V1_OK);
    assert(decoded.telemetry_sequence == telemetry.telemetry_sequence);
    assert(decoded.mcu_boot_id == telemetry.mcu_boot_id);
    assert(decoded.reset_epoch == telemetry.reset_epoch);
    assert(decoded.mcu_monotonic_time_us == telemetry.mcu_monotonic_time_us);
    assert(decoded.ticks_fl == telemetry.ticks_fl && decoded.ticks_fr == telemetry.ticks_fr
           && decoded.ticks_rl == telemetry.ticks_rl && decoded.ticks_rr == telemetry.ticks_rr);
    assert(decoded.last_accepted_command_sequence == telemetry.last_accepted_command_sequence);
    assert(decoded.mcu_fault_bits == telemetry.mcu_fault_bits);
    assert(decoded.estop_aux_active == telemetry.estop_aux_active);
}

static void test_invalid_codec_and_finite_helper(void)
{
    mecanum_uart_v1_frame_t frame;
    mecanum_uart_v1_command_t command;

    assert(mecanum_uart_v1_decode_wire_frame(i1_wire, sizeof(i1_wire), &frame)
           == MECANUM_UART_V1_ERROR_CRC);
    assert(mecanum_uart_v1_decode_wire_frame(i2_wire, sizeof(i2_wire), &frame)
           == MECANUM_UART_V1_ERROR_COBS);
    assert(mecanum_uart_v1_decode_wire_frame(i3_wire, sizeof(i3_wire), &frame)
           == MECANUM_UART_V1_ERROR_PAYLOAD_LENGTH);
    assert(mecanum_uart_v1_decode_wire_frame(i4_wire, sizeof(i4_wire), &frame)
           == MECANUM_UART_V1_ERROR_PROTOCOL_VERSION);
    assert(mecanum_uart_v1_decode_wire_frame(i5_wire, sizeof(i5_wire), &frame)
           == MECANUM_UART_V1_ERROR_MESSAGE_TYPE);
    assert(mecanum_uart_v1_decode_wire_frame(i6_wire, sizeof(i6_wire), &frame)
           == MECANUM_UART_V1_OK);
    assert(mecanum_uart_v1_parse_command(frame.payload, frame.payload_length, &command)
           == MECANUM_UART_V1_OK);
    assert(isnan(command.vx_mps));
    assert(!mecanum_uart_v1_command_is_finite(&command));
}

static void test_frame_boundary_rejection(void)
{
    uint8_t wrong_delimiter[sizeof(v1_wire)];
    uint8_t oversized[MECANUM_UART_V1_COBS_BUFFER_MINIMUM + 1U];
    uint8_t raw_too_small[sizeof(v1_raw) - 1U];
    uint8_t wire_too_small[sizeof(v1_wire) - 1U];
    size_t encoded_length = 0U;
    mecanum_uart_v1_frame_t frame;

    assert(mecanum_uart_v1_decode_wire_frame(v1_wire, sizeof(v1_wire) - 1U, &frame)
           == MECANUM_UART_V1_ERROR_DELIMITER);
    memcpy(wrong_delimiter, v1_wire, sizeof(wrong_delimiter));
    wrong_delimiter[sizeof(wrong_delimiter) - 1U] = UINT8_C(0xa5);
    assert(mecanum_uart_v1_decode_wire_frame(wrong_delimiter, sizeof(wrong_delimiter), &frame)
           == MECANUM_UART_V1_ERROR_DELIMITER);
    memset(oversized, UINT8_C(0x01), sizeof(oversized));
    oversized[sizeof(oversized) - 1U] = MECANUM_UART_V1_WIRE_DELIMITER;
    assert(mecanum_uart_v1_decode_wire_frame(oversized, sizeof(oversized), &frame)
           == MECANUM_UART_V1_ERROR_BUFFER_TOO_SMALL);
    assert(mecanum_uart_v1_build_raw_frame(MECANUM_UART_V1_MESSAGE_COMMAND,
                                            v1_payload, sizeof(v1_payload),
                                            raw_too_small, sizeof(raw_too_small),
                                            &encoded_length)
           == MECANUM_UART_V1_ERROR_BUFFER_TOO_SMALL);
    assert(mecanum_uart_v1_build_wire_frame(MECANUM_UART_V1_MESSAGE_COMMAND,
                                             v1_payload, sizeof(v1_payload),
                                             wire_too_small, sizeof(wire_too_small),
                                             &encoded_length)
           == MECANUM_UART_V1_ERROR_BUFFER_TOO_SMALL);
}

static void test_cobs_long_nonzero_run(void)
{
    uint8_t input[254];
    uint8_t encoded[256];
    uint8_t decoded[254];
    size_t encoded_length = 0U;
    size_t decoded_length = 0U;
    size_t index;

    for (index = 0U; index < sizeof(input); ++index) {
        input[index] = (uint8_t)(index + 1U);
    }
    assert(mecanum_uart_v1_cobs_encode(input, sizeof(input), encoded, sizeof(encoded),
                                        &encoded_length)
           == MECANUM_UART_V1_OK);
    assert(encoded_length == sizeof(input) + 2U);
    assert(encoded[0] == UINT8_C(0xff));
    assert(encoded[encoded_length - 1U] == UINT8_C(0x01));
    assert(mecanum_uart_v1_cobs_decode(encoded, encoded_length, decoded, sizeof(decoded),
                                        &decoded_length)
           == MECANUM_UART_V1_OK);
    assert(decoded_length == sizeof(input));
    assert(memcmp(decoded, input, sizeof(input)) == 0);
}

int main(void)
{
    static const uint8_t crc_input[] = {'1', '2', '3', '4', '5', '6', '7', '8', '9'};

    assert(mecanum_uart_v1_crc16_ccitt_false(crc_input, ARRAY_LENGTH(crc_input))
           == UINT16_C(0x29b1));
    test_v1_command();
    test_v2_config_request();
    test_config_status_vector(v3_payload, v3_raw, sizeof(v3_raw), v3_wire, sizeof(v3_wire),
                              UINT32_C(0x01020304), MECANUM_UART_V1_CONFIG_ACCEPTED,
                              MECANUM_UART_V1_REJECT_NONE);
    test_config_status_vector(v4_payload, v4_raw, sizeof(v4_raw), v4_wire, sizeof(v4_wire),
                              UINT32_C(0x01020305), MECANUM_UART_V1_CONFIG_REJECTED,
                              MECANUM_UART_V1_REJECT_HASH_MISMATCH);
    test_config_status_vector(v5_payload, v5_raw, sizeof(v5_raw), v5_wire, sizeof(v5_wire),
                              UINT32_C(0x01020306), MECANUM_UART_V1_CONFIG_REJECTED,
                              MECANUM_UART_V1_REJECT_LOCAL_CONFIG_INVALID);
    test_v6_telemetry();
    test_invalid_codec_and_finite_helper();
    test_frame_boundary_rejection();
    test_cobs_long_nonzero_run();

    puts("UART v1 codec host tests passed: V1-V6, I1-I5, and I6 finite helper.");
    puts("Codec boundary tests passed: delimiter, buffers, and 254-byte COBS run.");
    puts("I7-I9 are intentionally deferred to the ControlSafety/session module.");
    return 0;
}
